// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalesManagementSystem.Server.Persistence;

#nullable disable

namespace SalesManagementSystem.Server.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Open]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalesManagementSystem.Server.Persistence.Entities.SalesEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SalesGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SalesGroupId");

                    b.ToTable("SalesEntries");
                });

            modelBuilder.Entity("SalesManagementSystem.Server.Persistence.Entities.SalesGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SalesGroups");
                });

            modelBuilder.Entity("SalesManagementSystem.Server.Persistence.Entities.SalesEntry", b =>
                {
                    b.HasOne("SalesManagementSystem.Server.Persistence.Entities.SalesGroup", "SalesGroup")
                        .WithMany("SalesEntries")
                        .HasForeignKey("SalesGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesGroup");
                });

            modelBuilder.Entity("SalesManagementSystem.Server.Persistence.Entities.SalesGroup", b =>
                {
                    b.Navigation("SalesEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
