global using BetterErrors;
global using Microsoft.EntityFrameworkCore;
global using SalesManagementSystem.Server.Persistence;
global using SalesManagementSystem.Server.Persistence.Entities;
global using Nopen.NET;
global using Mapster;
global using MiniValidation;
global using SalesManagementSystem.Contracts;
global using SalesManagementSystem.Server.Helpers;
global using OneOf;
global using IHttpResult = Microsoft.AspNetCore.Http.IResult;
global using HttpResults = Microsoft.AspNetCore.Http.Results;